### ISSUE TITLE
[Data request] - Method counts

### ISSUE THREAD

**Issue by jaredsburrows** [retropiler/retropiler#4]
Can you compare the method counts with Java 7, Java 8 with Retrolambda and now Java 8 with Retropiler?

References:
Please read @JakeWharton's twitter post here: https://twitter.com/jakewharton/status/685531203710140418 and Github issue: https://github.com/orfjackal/retrolambda/issues/81

**Comment by JakeWharton** [comment]
This isn't a library or tool for converting lambdas and method references.

**Comment by jaredsburrows** [comment]
@gfx @JakeWharton So if convert an existing Java7 project to Java8 or convert an existing Retrolambda projec to Retropiler, it would be nice to know if it affects method count.

**Comment by gfx** [comment]
Yep, it doesn't convert lambda expressions. It just bundles standard library with some bytecode magic.

So method counts are already shown in http://www.methodscount.com/?lib=io.github.retropiler%3Aretropiler-runtime%3A0.0.2

Will add some explanation to README.

**Comment by jaredsburrows** [comment]
@gfx So how does it affect size of the DEX file. The method counts of the generated code?

**Comment by JakeWharton** [comment]
There is no generated code. It rewrites references to platform types to
reference a bundled library.

**Comment by gfx** [comment]
As @JakeWharton said, it generates nothing.

In fact, it currently depends on retrolambda (and will become depend on desugar in future) to convert lambda expressions to anonymous classes.

**Comment by jaredsburrows** [comment]
@JakeWharton @gfx Thanks for the explanation. I may use this if the Android gradle plugin 2.4.0 does not come out soon.

**Comment by JakeWharton** [comment]
This does nothing that the 2.4.0 plugin provides.

**Comment by jaredsburrows** [comment]
All I am saying is that we can finally target Java 8 with the 2.4.0 plugin; however, classes such as `Optional` are min sdk 24.

**Comment by JakeWharton** [comment]
You've been able to target the Java 8 language level with Retrolambda for 2
years now. The functionality of this tool is entirely orthogonal as it
focuses on the platform APIs which don't require the Java 8 language level.

**Comment by jaredsburrows** [comment]
@JakeWharton I know. I used to use Retrolambda.
